//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMProspecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProspectosInformacion
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido_Paterno { get; set; }
        public string Apellido_Materno { get; set; }
        public string Calle { get; set; }
        public Nullable<int> Numero { get; set; }
        public string Colonia { get; set; }
        public Nullable<int> Codigo_Postal { get; set; }
        public Nullable<long> Telefono { get; set; }
        public string Rfc { get; set; }
        public string Estatus { get; set; }
        public string Comentarios { get; set; }
        public byte[] Archivos { get; set; }
        public string NombreArchivo { get; set; }
    }
}
